### ISSUE TITLE
Errors still appear if I go from an auth page to the other

### ISSUE THREAD

**Issue by felipefreitag** [seasonedcc/croods-auth#8]
Steps to reproduce:
- Go to sign in. Generate an error like an invalid email
- Navigate to sign up. The error will still be there
It also happens vice-versa.

<img width="723" alt="Screen Shot 2019-06-17 at 15 02 26" src="https://user-images.githubusercontent.com/6249611/59626007-11c36380-9111-11e9-9250-5fa0f4c93aa7.png">
<img width="673" alt="Screen Shot 2019-06-17 at 15 02 31" src="https://user-images.githubusercontent.com/6249611/59626008-11c36380-9111-11e9-8ea1-543648e24646.png">

**Comment by gustavoguichard** [comment]
possible quick solution: can't you use the `seasoned-flash` to display this error so it'll vanish after few seconds?
I know it is a limitation due to the fact we use shared state though...

I can also clear the error whenever the component unmounts... it is also going to work in this case, not sure about different implementations in the future .

What do you think @felipefreitag?

**Comment by felipefreitag** [comment]
I think the state should be cleared when going from one to the other, to avoid having leftovers. Sometimes we test for a specific condition - for example, to disable the button if there are errors - that would break.

**Comment by gustavoguichard** [comment]
Do you think we can rely on the component unmounting for now? @felipefreitag

**Comment by felipefreitag** [comment]
I'm far away from implementation, but I think so!

**Comment by gustavoguichard** [comment]
@felipefreitag this should be solved in `2.2.0`
